language: node_js
matrix:
  include:
    - node_js: "4.3.2"
    - node_js: "5"
    - node_js: "6"
    - node_js: "7"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
     - chrome-linux
     - lighthouse-extension/node_modules
install:
  - npm install
before_script:
  - npm i -g typescript@2.0
  - npm --prefix ./lighthouse-extension install ./lighthouse-extension
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./lighthouse-core/scripts/download-chrome.sh
  - cd lighthouse-cli && tsc && cd ..
script:
  - if [[ $(node -v) =~ ^v4.* ]]; then export __node_harmony=--harmony; fi
  - npm run lint
  - npm run unit
  - npm run smoke
  - npm run smokehouse
  - cd lighthouse-extension
  - gulp build -- $__node_harmony
  - cd ..
after_success:
  - npm run coveralls
