language: node_js
matrix:
  include:
    - node_js: "4.3.2"
    - node_js: "5.0"
    - node_js: "node"
sudo: required
dist: trusty
cache:
   directories:
     - node_modules
     - chrome-linux
     - lighthouse-extension/node_modules
before_script:
  - npm --prefix ./lighthouse-extension install ./lighthouse-extension
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - ./lighthouse-core/scripts/download-chrome.sh
  - start-stop-daemon --start --background --exec $(pwd)/lighthouse-core/scripts/launch-chrome.sh
script:
  - if [[ $(node -v) =~ ^v4.* ]]; then export __node_harmony=--harmony; fi
  - npm run lint
  - npm run unit
  - npm run closure
  - npm run coveralls
  - npm run smoke
  - cd lighthouse-extension
  - gulp build
